### ISSUE TITLE
Suggestie: GDAL noemen

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/ogc-api-features-guideline#1]
In hfd 2 stap 7 kan eventueel GDAL nog toegevoegd worden als tool waarmee je datasets kan transformeren. Het is niet van dezelfde orde als FME en Hale, dus ik weet niet helemaal zeker of het in dit rijtje past.

**Comment by PB-GNM** [comment]
Als ik het goed begrepen heb is GDAL vooral voor het omzetten naar een ander file-format en HALE en FME kunnen ook hele structuren veranderen. Die structuur is niet altijd van belang, dus dan zou GDAL ook een optie kunnen zijn.
Ik zal het daarom toevoegen. Dank voor de tip.
